module.exports = {
    CREATE_USER_REQUEST : "CREATE_USER_REQUEST",
    CREATE_USER_FAILURE : "CREATE_USER_FAILURE",
    FETCH_CURRENT_USER_REQUEST : "FETCH_CURRENT_USER_REQUEST",
    FETCH_CURRENT_USER_SUCCESS : "FETCH_CURRENT_USER_SUCCESS",
}